// Prayer times (UOIF method=12, Lyon, France)
// Pre-Ramadan (Feb 9 – Feb 17): Fajr 06:46, Dhuhr 12:55, Asr 15:32, Maghrib 17:58, Isha 19:05
// Ramadan (Feb 18 – Mar 23):    Fajr 06:08, Dhuhr 12:52, Asr 15:57, Maghrib 18:33, Isha 19:37

export const defaultTabs = [
  {
    label: "Pre-Ramadan",
    dates: "Feb 9 \u2192 Feb 17",
    order: 0,
    days: {
      monday: {
        label: "Monday",
        blocks: [
          { id: "p-m-1", time: "06:30", activity: "Wake up", type: "neutral", icon: "\u23f0" },
          { id: "p-m-2", time: "06:46", activity: "Fajr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-m-3", time: "07:30", activity: "Breakfast + French self-study", type: "study", icon: "\ud83d\udcda" },
          { id: "p-m-4", time: "08:30", activity: "Commute / Prep", type: "neutral", icon: "\ud83d\udeb6" },
          { id: "p-m-5", time: "09:00", activity: "French Course", type: "course", icon: "\ud83c\uddeb\ud83c\uddf7" },
          { id: "p-m-6", time: "12:30", activity: "Lunch", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "p-m-7", time: "12:55", activity: "Dhuhr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-m-8", time: "13:30", activity: "Interview Prep / Job Search", type: "work", icon: "\ud83d\udcbc" },
          { id: "p-m-9", time: "15:00", activity: "Side Projects", type: "project", icon: "\u26a1" },
          { id: "p-m-10", time: "15:32", activity: "Asr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-m-11", time: "16:00", activity: "Sport (Gym / Climbing / Swimming)", type: "sport", icon: "\ud83d\udcaa" },
          { id: "p-m-12", time: "17:30", activity: "Dinner + Rest", type: "rest", icon: "\ud83c\udf7d\ufe0f" },
          { id: "p-m-13", time: "17:58", activity: "Maghrib + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-m-14", time: "18:30", activity: "Islamic Lectures / Free time", type: "spiritual", icon: "\ud83c\udfa7" },
          { id: "p-m-15", time: "19:05", activity: "Isha + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-m-16", time: "19:30", activity: "Wind down / Rest", type: "rest", icon: "\ud83d\ude34" },
        ],
      },
      tuesday: {
        label: "Tuesday",
        blocks: [
          { id: "p-tu-1", time: "06:30", activity: "Wake up", type: "neutral", icon: "\u23f0" },
          { id: "p-tu-2", time: "06:46", activity: "Fajr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-tu-3", time: "07:30", activity: "Breakfast + French self-study", type: "study", icon: "\ud83d\udcda" },
          { id: "p-tu-4", time: "08:30", activity: "Commute / Prep", type: "neutral", icon: "\ud83d\udeb6" },
          { id: "p-tu-5", time: "09:00", activity: "French Course", type: "course", icon: "\ud83c\uddeb\ud83c\uddf7" },
          { id: "p-tu-6", time: "12:30", activity: "Lunch", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "p-tu-7", time: "12:55", activity: "Dhuhr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-tu-8", time: "13:30", activity: "Side Projects (deep work)", type: "project", icon: "\u26a1" },
          { id: "p-tu-9", time: "15:00", activity: "Interview Prep / Job Search", type: "work", icon: "\ud83d\udcbc" },
          { id: "p-tu-10", time: "15:32", activity: "Asr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-tu-11", time: "16:00", activity: "Free time / Social", type: "rest", icon: "\u2615" },
          { id: "p-tu-12", time: "17:30", activity: "Dinner", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "p-tu-13", time: "17:58", activity: "Maghrib + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-tu-14", time: "18:30", activity: "French review", type: "study", icon: "\ud83d\udcda" },
          { id: "p-tu-15", time: "19:05", activity: "Isha + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-tu-16", time: "19:30", activity: "Wind down / Rest", type: "rest", icon: "\ud83d\ude34" },
        ],
      },
      wednesday: {
        label: "Wednesday",
        blocks: [
          { id: "p-w-1", time: "06:30", activity: "Wake up", type: "neutral", icon: "\u23f0" },
          { id: "p-w-2", time: "06:46", activity: "Fajr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-w-3", time: "07:30", activity: "Breakfast + French self-study", type: "study", icon: "\ud83d\udcda" },
          { id: "p-w-4", time: "08:30", activity: "Commute / Prep", type: "neutral", icon: "\ud83d\udeb6" },
          { id: "p-w-5", time: "09:00", activity: "French Course", type: "course", icon: "\ud83c\uddeb\ud83c\uddf7" },
          { id: "p-w-6", time: "12:30", activity: "Lunch", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "p-w-7", time: "12:55", activity: "Dhuhr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-w-8", time: "13:30", activity: "Therapy (biweekly)", type: "therapy", icon: "\ud83e\udde0" },
          { id: "p-w-9", time: "14:30", activity: "Side Projects", type: "project", icon: "\u26a1" },
          { id: "p-w-10", time: "15:32", activity: "Asr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-w-11", time: "16:00", activity: "Sport (Gym / Climbing / Swimming)", type: "sport", icon: "\ud83d\udcaa" },
          { id: "p-w-12", time: "17:30", activity: "Dinner", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "p-w-13", time: "17:58", activity: "Maghrib + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-w-14", time: "18:30", activity: "Islamic Lectures", type: "spiritual", icon: "\ud83c\udfa7" },
          { id: "p-w-15", time: "19:05", activity: "Isha + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-w-16", time: "19:30", activity: "Wind down / Rest", type: "rest", icon: "\ud83d\ude34" },
        ],
      },
      thursday: {
        label: "Thursday",
        blocks: [
          { id: "p-th-1", time: "06:30", activity: "Wake up", type: "neutral", icon: "\u23f0" },
          { id: "p-th-2", time: "06:46", activity: "Fajr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-th-3", time: "07:30", activity: "Breakfast + French self-study", type: "study", icon: "\ud83d\udcda" },
          { id: "p-th-4", time: "08:30", activity: "Commute / Prep", type: "neutral", icon: "\ud83d\udeb6" },
          { id: "p-th-5", time: "09:00", activity: "French Course", type: "course", icon: "\ud83c\uddeb\ud83c\uddf7" },
          { id: "p-th-6", time: "12:30", activity: "Lunch", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "p-th-7", time: "12:55", activity: "Dhuhr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-th-8", time: "13:30", activity: "Interview Prep / Job Search", type: "work", icon: "\ud83d\udcbc" },
          { id: "p-th-9", time: "15:00", activity: "Side Projects", type: "project", icon: "\u26a1" },
          { id: "p-th-10", time: "15:32", activity: "Asr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-th-11", time: "16:00", activity: "Sport (Gym / Climbing / Swimming)", type: "sport", icon: "\ud83d\udcaa" },
          { id: "p-th-12", time: "17:30", activity: "Dinner", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "p-th-13", time: "17:58", activity: "Maghrib + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-th-14", time: "18:30", activity: "Free time", type: "rest", icon: "\u2615" },
          { id: "p-th-15", time: "19:05", activity: "Isha + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-th-16", time: "19:30", activity: "Wind down / Rest", type: "rest", icon: "\ud83d\ude34" },
        ],
      },
      friday: {
        label: "Friday",
        blocks: [
          { id: "p-f-1", time: "06:30", activity: "Wake up", type: "neutral", icon: "\u23f0" },
          { id: "p-f-2", time: "06:46", activity: "Fajr + Quran (4 pages) + Surah Al-Kahf", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-f-3", time: "07:30", activity: "Breakfast + French self-study", type: "study", icon: "\ud83d\udcda" },
          { id: "p-f-4", time: "08:30", activity: "Commute / Prep", type: "neutral", icon: "\ud83d\udeb6" },
          { id: "p-f-5", time: "09:00", activity: "French Course", type: "course", icon: "\ud83c\uddeb\ud83c\uddf7" },
          { id: "p-f-6", time: "12:55", activity: "Jumu'ah Prayer + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-f-7", time: "14:00", activity: "Side Projects (deep work)", type: "project", icon: "\u26a1" },
          { id: "p-f-8", time: "15:32", activity: "Asr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-f-9", time: "16:00", activity: "Free time / Social / DJing", type: "rest", icon: "\ud83c\udfa7" },
          { id: "p-f-10", time: "17:30", activity: "Dinner", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "p-f-11", time: "17:58", activity: "Maghrib + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-f-12", time: "18:30", activity: "Free evening", type: "rest", icon: "\u2615" },
          { id: "p-f-13", time: "19:05", activity: "Isha + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-f-14", time: "19:30", activity: "Rest", type: "rest", icon: "\ud83d\ude34" },
        ],
      },
      saturday: {
        label: "Saturday",
        blocks: [
          { id: "p-sa-1", time: "07:00", activity: "Wake up (sleep in)", type: "rest", icon: "\ud83d\ude34" },
          { id: "p-sa-2", time: "07:15", activity: "Fajr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-sa-3", time: "08:00", activity: "Breakfast + Chill", type: "rest", icon: "\u2615" },
          { id: "p-sa-4", time: "09:30", activity: "Side Projects (deep work)", type: "project", icon: "\u26a1" },
          { id: "p-sa-5", time: "12:00", activity: "French review", type: "study", icon: "\ud83d\udcda" },
          { id: "p-sa-6", time: "12:30", activity: "Lunch", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "p-sa-7", time: "12:55", activity: "Dhuhr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-sa-8", time: "13:30", activity: "Free time / Errands / Social", type: "rest", icon: "\u2615" },
          { id: "p-sa-9", time: "15:32", activity: "Asr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-sa-10", time: "16:00", activity: "Sport (Gym / Climbing / Swimming)", type: "sport", icon: "\ud83d\udcaa" },
          { id: "p-sa-11", time: "17:30", activity: "Dinner", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "p-sa-12", time: "17:58", activity: "Maghrib + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-sa-13", time: "18:30", activity: "Islamic Lectures / Free time", type: "spiritual", icon: "\ud83c\udfa7" },
          { id: "p-sa-14", time: "19:05", activity: "Isha + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-sa-15", time: "19:30", activity: "Rest", type: "rest", icon: "\ud83d\ude34" },
        ],
      },
      sunday: {
        label: "Sunday",
        blocks: [
          { id: "p-su-1", time: "07:00", activity: "Wake up (sleep in)", type: "rest", icon: "\ud83d\ude34" },
          { id: "p-su-2", time: "07:15", activity: "Fajr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-su-3", time: "08:00", activity: "Breakfast", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "p-su-4", time: "09:00", activity: "Self-work / Reflection / Journaling", type: "therapy", icon: "\ud83e\udde0" },
          { id: "p-su-5", time: "10:00", activity: "Interview Prep", type: "work", icon: "\ud83d\udcbc" },
          { id: "p-su-6", time: "12:00", activity: "Side Projects", type: "project", icon: "\u26a1" },
          { id: "p-su-7", time: "12:30", activity: "Lunch", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "p-su-8", time: "12:55", activity: "Dhuhr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-su-9", time: "13:30", activity: "Week planning / Review", type: "work", icon: "\ud83d\udccb" },
          { id: "p-su-10", time: "14:30", activity: "Islamic Lectures", type: "spiritual", icon: "\ud83c\udfa7" },
          { id: "p-su-11", time: "15:00", activity: "Free time", type: "rest", icon: "\u2615" },
          { id: "p-su-12", time: "15:32", activity: "Asr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-su-13", time: "16:00", activity: "French review / Prep for week", type: "study", icon: "\ud83d\udcda" },
          { id: "p-su-14", time: "17:30", activity: "Dinner", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "p-su-15", time: "17:58", activity: "Maghrib + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-su-16", time: "18:30", activity: "Rest", type: "rest", icon: "\ud83c\udf3f" },
          { id: "p-su-17", time: "19:05", activity: "Isha + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "p-su-18", time: "19:30", activity: "Early sleep \u2014 week starts tomorrow", type: "rest", icon: "\ud83d\ude34" },
        ],
      },
    },
  },
  {
    label: "Ramadan",
    dates: "Feb 18 \u2192 Mar 23",
    order: 1,
    days: {
      monday: {
        label: "Monday",
        blocks: [
          { id: "r-m-1", time: "05:45", activity: "Wake up + Suhoor", type: "spiritual", icon: "\ud83c\udf19" },
          { id: "r-m-2", time: "06:08", activity: "Fajr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-m-3", time: "07:00", activity: "French self-study", type: "study", icon: "\ud83d\udcda" },
          { id: "r-m-4", time: "08:30", activity: "Commute / Prep", type: "neutral", icon: "\ud83d\udeb6" },
          { id: "r-m-5", time: "09:00", activity: "French Course", type: "course", icon: "\ud83c\uddeb\ud83c\uddf7" },
          { id: "r-m-6", time: "12:52", activity: "Dhuhr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-m-7", time: "13:30", activity: "Interview Prep / Job Search", type: "work", icon: "\ud83d\udcbc" },
          { id: "r-m-8", time: "15:00", activity: "Side Projects", type: "project", icon: "\u26a1" },
          { id: "r-m-9", time: "15:57", activity: "Asr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-m-10", time: "16:30", activity: "Islamic Lectures", type: "spiritual", icon: "\ud83c\udfa7" },
          { id: "r-m-11", time: "18:00", activity: "Wind down / Prep Iftar", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "r-m-12", time: "18:33", activity: "Maghrib + Iftar + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-m-13", time: "19:15", activity: "Sport (Gym / Climbing / Swimming)", type: "sport", icon: "\ud83d\udcaa" },
          { id: "r-m-14", time: "19:37", activity: "Isha + Tarawih + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-m-15", time: "21:30", activity: "Wind down / Rest", type: "rest", icon: "\ud83d\ude34" },
        ],
      },
      tuesday: {
        label: "Tuesday",
        blocks: [
          { id: "r-tu-1", time: "05:45", activity: "Wake up + Suhoor", type: "spiritual", icon: "\ud83c\udf19" },
          { id: "r-tu-2", time: "06:08", activity: "Fajr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-tu-3", time: "07:00", activity: "French self-study", type: "study", icon: "\ud83d\udcda" },
          { id: "r-tu-4", time: "08:30", activity: "Commute / Prep", type: "neutral", icon: "\ud83d\udeb6" },
          { id: "r-tu-5", time: "09:00", activity: "French Course", type: "course", icon: "\ud83c\uddeb\ud83c\uddf7" },
          { id: "r-tu-6", time: "12:52", activity: "Dhuhr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-tu-7", time: "13:30", activity: "Side Projects", type: "project", icon: "\u26a1" },
          { id: "r-tu-8", time: "15:00", activity: "Interview Prep / Job Search", type: "work", icon: "\ud83d\udcbc" },
          { id: "r-tu-9", time: "15:57", activity: "Asr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-tu-10", time: "16:30", activity: "French self-study / Review", type: "study", icon: "\ud83d\udcda" },
          { id: "r-tu-11", time: "18:00", activity: "Wind down / Prep Iftar", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "r-tu-12", time: "18:33", activity: "Maghrib + Iftar + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-tu-13", time: "19:15", activity: "Rest / Light walk", type: "rest", icon: "\ud83c\udf3f" },
          { id: "r-tu-14", time: "19:37", activity: "Isha + Tarawih + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-tu-15", time: "21:30", activity: "Wind down / Rest", type: "rest", icon: "\ud83d\ude34" },
        ],
      },
      wednesday: {
        label: "Wednesday",
        blocks: [
          { id: "r-w-1", time: "05:45", activity: "Wake up + Suhoor", type: "spiritual", icon: "\ud83c\udf19" },
          { id: "r-w-2", time: "06:08", activity: "Fajr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-w-3", time: "07:00", activity: "French self-study", type: "study", icon: "\ud83d\udcda" },
          { id: "r-w-4", time: "08:30", activity: "Commute / Prep", type: "neutral", icon: "\ud83d\udeb6" },
          { id: "r-w-5", time: "09:00", activity: "French Course", type: "course", icon: "\ud83c\uddeb\ud83c\uddf7" },
          { id: "r-w-6", time: "12:52", activity: "Dhuhr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-w-7", time: "13:30", activity: "Therapy (biweekly)", type: "therapy", icon: "\ud83e\udde0" },
          { id: "r-w-8", time: "14:30", activity: "Interview Prep / Job Search", type: "work", icon: "\ud83d\udcbc" },
          { id: "r-w-9", time: "15:57", activity: "Asr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-w-10", time: "16:30", activity: "Side Projects", type: "project", icon: "\u26a1" },
          { id: "r-w-11", time: "18:00", activity: "Wind down / Prep Iftar", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "r-w-12", time: "18:33", activity: "Maghrib + Iftar + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-w-13", time: "19:15", activity: "Sport (Gym / Climbing / Swimming)", type: "sport", icon: "\ud83d\udcaa" },
          { id: "r-w-14", time: "19:37", activity: "Isha + Tarawih + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-w-15", time: "21:30", activity: "Wind down / Rest", type: "rest", icon: "\ud83d\ude34" },
        ],
      },
      thursday: {
        label: "Thursday",
        blocks: [
          { id: "r-th-1", time: "05:45", activity: "Wake up + Suhoor", type: "spiritual", icon: "\ud83c\udf19" },
          { id: "r-th-2", time: "06:08", activity: "Fajr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-th-3", time: "07:00", activity: "French self-study", type: "study", icon: "\ud83d\udcda" },
          { id: "r-th-4", time: "08:30", activity: "Commute / Prep", type: "neutral", icon: "\ud83d\udeb6" },
          { id: "r-th-5", time: "09:00", activity: "French Course", type: "course", icon: "\ud83c\uddeb\ud83c\uddf7" },
          { id: "r-th-6", time: "12:52", activity: "Dhuhr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-th-7", time: "13:30", activity: "Interview Prep / Job Search", type: "work", icon: "\ud83d\udcbc" },
          { id: "r-th-8", time: "15:00", activity: "Islamic Lectures", type: "spiritual", icon: "\ud83c\udfa7" },
          { id: "r-th-9", time: "15:57", activity: "Asr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-th-10", time: "16:30", activity: "Side Projects", type: "project", icon: "\u26a1" },
          { id: "r-th-11", time: "18:00", activity: "Wind down / Prep Iftar", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "r-th-12", time: "18:33", activity: "Maghrib + Iftar + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-th-13", time: "19:15", activity: "Sport (Gym / Climbing / Swimming)", type: "sport", icon: "\ud83d\udcaa" },
          { id: "r-th-14", time: "19:37", activity: "Isha + Tarawih + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-th-15", time: "21:30", activity: "Wind down / Rest", type: "rest", icon: "\ud83d\ude34" },
        ],
      },
      friday: {
        label: "Friday",
        blocks: [
          { id: "r-f-1", time: "05:45", activity: "Wake up + Suhoor", type: "spiritual", icon: "\ud83c\udf19" },
          { id: "r-f-2", time: "06:08", activity: "Fajr + Quran (4 pages) + Surah Al-Kahf", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-f-3", time: "07:00", activity: "French self-study", type: "study", icon: "\ud83d\udcda" },
          { id: "r-f-4", time: "08:30", activity: "Commute / Prep", type: "neutral", icon: "\ud83d\udeb6" },
          { id: "r-f-5", time: "09:00", activity: "French Course", type: "course", icon: "\ud83c\uddeb\ud83c\uddf7" },
          { id: "r-f-6", time: "12:52", activity: "Jumu'ah Prayer + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-f-7", time: "14:00", activity: "Side Projects (deep work)", type: "project", icon: "\u26a1" },
          { id: "r-f-8", time: "15:57", activity: "Asr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-f-9", time: "16:30", activity: "Free time / Socialize", type: "rest", icon: "\u2615" },
          { id: "r-f-10", time: "18:00", activity: "Prep Iftar", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "r-f-11", time: "18:33", activity: "Maghrib + Iftar + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-f-12", time: "19:15", activity: "Rest / Social", type: "rest", icon: "\ud83c\udf3f" },
          { id: "r-f-13", time: "19:37", activity: "Isha + Tarawih + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-f-14", time: "21:30", activity: "Wind down / Rest", type: "rest", icon: "\ud83d\ude34" },
        ],
      },
      saturday: {
        label: "Saturday",
        blocks: [
          { id: "r-sa-1", time: "05:45", activity: "Wake up + Suhoor", type: "spiritual", icon: "\ud83c\udf19" },
          { id: "r-sa-2", time: "06:08", activity: "Fajr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-sa-3", time: "07:00", activity: "Sleep / Rest", type: "rest", icon: "\ud83d\ude34" },
          { id: "r-sa-4", time: "10:00", activity: "French self-study (review week)", type: "study", icon: "\ud83d\udcda" },
          { id: "r-sa-5", time: "11:30", activity: "Side Projects (deep work)", type: "project", icon: "\u26a1" },
          { id: "r-sa-6", time: "12:52", activity: "Dhuhr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-sa-7", time: "13:30", activity: "Islamic Lectures", type: "spiritual", icon: "\ud83c\udfa7" },
          { id: "r-sa-8", time: "14:30", activity: "Free time / Errands / Social", type: "rest", icon: "\u2615" },
          { id: "r-sa-9", time: "15:57", activity: "Asr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-sa-10", time: "16:30", activity: "Interview Prep", type: "work", icon: "\ud83d\udcbc" },
          { id: "r-sa-11", time: "18:00", activity: "Prep Iftar", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "r-sa-12", time: "18:33", activity: "Maghrib + Iftar + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-sa-13", time: "19:15", activity: "Sport (Gym / Climbing / Swimming)", type: "sport", icon: "\ud83d\udcaa" },
          { id: "r-sa-14", time: "19:37", activity: "Isha + Tarawih + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-sa-15", time: "21:30", activity: "Wind down / Rest", type: "rest", icon: "\ud83d\ude34" },
        ],
      },
      sunday: {
        label: "Sunday",
        blocks: [
          { id: "r-su-1", time: "05:45", activity: "Wake up + Suhoor", type: "spiritual", icon: "\ud83c\udf19" },
          { id: "r-su-2", time: "06:08", activity: "Fajr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-su-3", time: "07:00", activity: "Sleep / Rest", type: "rest", icon: "\ud83d\ude34" },
          { id: "r-su-4", time: "10:00", activity: "Self-work / Reflection / Journaling", type: "therapy", icon: "\ud83e\udde0" },
          { id: "r-su-5", time: "11:00", activity: "Side Projects", type: "project", icon: "\u26a1" },
          { id: "r-su-6", time: "12:52", activity: "Dhuhr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-su-7", time: "13:30", activity: "Islamic Lectures", type: "spiritual", icon: "\ud83c\udfa7" },
          { id: "r-su-8", time: "14:30", activity: "Week planning / Review", type: "work", icon: "\ud83d\udccb" },
          { id: "r-su-9", time: "15:30", activity: "Free time", type: "rest", icon: "\u2615" },
          { id: "r-su-10", time: "15:57", activity: "Asr + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-su-11", time: "16:30", activity: "French review / Prep for week", type: "study", icon: "\ud83d\udcda" },
          { id: "r-su-12", time: "18:00", activity: "Prep Iftar", type: "neutral", icon: "\ud83c\udf7d\ufe0f" },
          { id: "r-su-13", time: "18:33", activity: "Maghrib + Iftar + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-su-14", time: "19:15", activity: "Rest", type: "rest", icon: "\ud83c\udf3f" },
          { id: "r-su-15", time: "19:37", activity: "Isha + Tarawih + Quran (4 pages)", type: "prayer", icon: "\ud83d\udd4c" },
          { id: "r-su-16", time: "21:30", activity: "Early sleep \u2014 week starts tomorrow", type: "rest", icon: "\ud83d\ude34" },
        ],
      },
    },
  },
];
